import { Product, SuperCategory, SuperCategoryId } from "@/types";

export const superCategories: SuperCategory[] = [
  {
    id: "iluminacion-led-neon",
    name: "Iluminación LED & Neón Flex",
    slug: "iluminacion-led-neon",
    icon: "Lightbulb",
    description: "Proyectores, cintas, ampolletas y drivers",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    color: "bg-amber-500",
    subcategories: [
      { id: "proyectores-led", name: "Proyectores LED", slug: "proyectores-led", count: 86 },
      { id: "cintas-led", name: "Cintas LED & Neón Flex", slug: "cintas-led", count: 124 },
      { id: "ampolletas-led", name: "Ampolletas & Paneles LED", slug: "ampolletas-led", count: 210 },
      { id: "drivers-fuentes", name: "Drivers & Transformadores", slug: "drivers-fuentes", count: 64 },
      { id: "repuestos-led", name: "Repuestos & Accesorios LED", slug: "repuestos-led", count: 92 },
      { id: "iluminacion-industrial", name: "Iluminación Industrial", slug: "iluminacion-industrial", count: 45 },
    ],
  },
  {
    id: "herramientas-maquinarias",
    name: "Herramientas & Maquinarias",
    slug: "herramientas-maquinarias",
    icon: "Wrench",
    description: "Crimpadoras, prensas y herramientas pro",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=300&fit=crop",
    color: "bg-slate-700",
    subcategories: [
      { id: "crimpadoras", name: "Crimpadoras & Ponchadoras", slug: "crimpadoras", count: 38 },
      { id: "prensas-hidraulicas", name: "Prensas Hidráulicas", slug: "prensas-hidraulicas", count: 22 },
      { id: "pelacables", name: "Pelacables & Alicates", slug: "pelacables", count: 76 },
      { id: "taladros", name: "Taladros & Atornilladores", slug: "taladros", count: 54 },
      { id: "sierras", name: "Sierras & Esmeriles", slug: "sierras", count: 41 },
      { id: "herramientas-electricista", name: "Kit Electricista Profesional", slug: "herramientas-electricista", count: 67 },
    ],
  },
  {
    id: "instrumentos-medicion",
    name: "Instrumentos de Medición & Térmicos",
    slug: "instrumentos-medicion",
    icon: "Gauge",
    description: "Multímetros, pirómetros y cámaras termográficas",
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400&h=300&fit=crop",
    color: "bg-cyan-600",
    subcategories: [
      { id: "multimetros", name: "Multímetros Digitales", slug: "multimetros", count: 48 },
      { id: "pinzas-amperimetricas", name: "Pinzas Amperimétricas", slug: "pinzas-amperimetricas", count: 32 },
      { id: "pirometros", name: "Pirómetros Infrarrojos", slug: "pirometros", count: 18 },
      { id: "camaras-termograficas", name: "Cámaras Termográficas", slug: "camaras-termograficas", count: 12 },
      { id: "medidores-distancia", name: "Medidores Láser", slug: "medidores-distancia", count: 26 },
      { id: "testers-red", name: "Testers de Red & Cable", slug: "testers-red", count: 34 },
    ],
  },
  {
    id: "tubos-lamparas-especiales",
    name: "Tubos & Lámparas Especiales",
    slug: "tubos-lamparas-especiales",
    icon: "FlaskConical",
    description: "UV-C germicidas, fotocopiadoras y más",
    image: "https://images.unsplash.com/photo-1613665813446-82a78c468a1d?w=400&h=300&fit=crop",
    color: "bg-violet-600",
    subcategories: [
      { id: "germicidas-uvc", name: "Tubos Germicidas UV-C", slug: "germicidas-uvc", count: 28 },
      { id: "atrapa-mosquitos", name: "Lámparas Atrapa Mosquitos", slug: "atrapa-mosquitos", count: 19 },
      { id: "fotocopiadoras", name: "Lámparas Fotocopiadoras", slug: "fotocopiadoras", count: 14 },
      { id: "halogenas", name: "Halógenas & HMI", slug: "halogenas", count: 22 },
      { id: "infrarrojas", name: "Lámparas Infrarrojas", slug: "infrarrojas", count: 16 },
    ],
  },
  {
    id: "fuentes-poder-soldadura",
    name: "Fuentes de Poder & Soldadura",
    slug: "fuentes-poder-soldadura",
    icon: "Zap",
    description: "Estaciones de calor y transformadores",
    image: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=400&h=300&fit=crop",
    color: "bg-orange-600",
    subcategories: [
      { id: "estaciones-soldado", name: "Estaciones de Soldado", slug: "estaciones-soldado", count: 31 },
      { id: "cautines", name: "Cautines & Pistolas", slug: "cautines", count: 44 },
      { id: "fuentes-laboratorio", name: "Fuentes de Laboratorio", slug: "fuentes-laboratorio", count: 26 },
      { id: "transformadores-12v", name: "Transformadores 12V/24V", slug: "transformadores-12v", count: 38 },
      { id: "inversores", name: "Inversores & UPS", slug: "inversores", count: 21 },
    ],
  },
  {
    id: "pilas-baterias-cargadores",
    name: "Pilas, Baterías & Cargadores",
    slug: "pilas-baterias-cargadores",
    icon: "BatteryCharging",
    description: "Litio, selladas y power banks",
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=300&fit=crop",
    color: "bg-emerald-600",
    subcategories: [
      { id: "pilas-litio", name: "Pilas de Litio 18650/21700", slug: "pilas-litio", count: 52 },
      { id: "baterias-selladas", name: "Baterías Selladas 12V", slug: "baterias-selladas", count: 36 },
      { id: "cargadores-inteligentes", name: "Cargadores Inteligentes", slug: "cargadores-inteligentes", count: 41 },
      { id: "power-banks", name: "Power Banks & Estaciones", slug: "power-banks", count: 29 },
      { id: "baterias-herramientas", name: "Baterías para Herramientas", slug: "baterias-herramientas", count: 33 },
    ],
  },
  {
    id: "seguridad-control-electrico",
    name: "Seguridad & Control Eléctrico",
    slug: "seguridad-control-electrico",
    icon: "ShieldCheck",
    description: "Interruptores, disyuntores y alarmas",
    image: "/Seguridad & Control Electrico.png",
    color: "bg-red-600",
    subcategories: [
      { id: "interruptores", name: "Interruptores & Enchufes", slug: "interruptores", count: 88 },
      { id: "disyuntores", name: "Disyuntores & Diferenciales", slug: "disyuntores", count: 64 },
      { id: "tableros", name: "Tableros & Gabinetes", slug: "tableros", count: 32 },
      { id: "alarmas", name: "Alarmas & Sensores", slug: "alarmas", count: 27 },
      { id: "camaras-seguridad", name: "Cámaras de Seguridad", slug: "camaras-seguridad", count: 35 },
      { id: "domotica", name: "Domótica & Smart Home", slug: "domotica", count: 42 },
    ],
  },
  {
    id: "electronica-miscelaneos",
    name: "Electrónica & Misceláneos",
    slug: "electronica-miscelaneos",
    icon: "Cpu",
    description: "Componentes y accesorios varios",
    image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=300&fit=crop",
    color: "bg-indigo-600",
    subcategories: [
      { id: "componentes", name: "Componentes Electrónicos", slug: "componentes", count: 156 },
      { id: "protoboard", name: "Protoboard & Arduino", slug: "protoboard", count: 72 },
      { id: "cables", name: "Cables & Conectores", slug: "cables", count: 98 },
      { id: "audio", name: "Audio & Parlantes", slug: "audio", count: 31 },
      { id: "iluminacion-deco", name: "Iluminación Decorativa", slug: "iluminacion-deco", count: 54 },
    ],
  },
];

// ---- Fábrica de productos para poblar los sliders de sección ----
function makeProduct(p: {
  id: string;
  categoryId: SuperCategoryId;
  subcategory: string;
  name: string;
  brand: string;
  price: number;
  images: [string, string];
  originalPrice?: number;
  rating?: number;
  reviewCount?: number;
  stock?: number;
  soldCount?: number;
  isFeatured?: boolean;
  isBestSeller?: boolean;
  secCertified?: boolean;
}): Product {
  const originalPrice = p.originalPrice;
  const discount = originalPrice ? Math.round((1 - p.price / originalPrice) * 100) : undefined;
  return {
    id: p.id,
    sku: p.id.toUpperCase(),
    name: p.name,
    slug: p.id,
    description: `${p.name}. Producto de línea Starshop con despacho 24h en RM, despacho a todo Chile y garantía oficial.`,
    shortDescription: p.name,
    categoryId: p.categoryId,
    subcategory: p.subcategory,
    brand: p.brand,
    images: p.images,
    price: p.price,
    originalPrice,
    discount,
    rating: p.rating ?? 4.5,
    reviewCount: p.reviewCount ?? 60,
    stock: p.stock ?? 120,
    soldCount: p.soldCount ?? 240,
    isFlashSale: false,
    isFeatured: p.isFeatured ?? false,
    isBestSeller: p.isBestSeller ?? false,
    secCertified: p.secCertified ?? false,
    warranty: "1 año",
    specs: {},
    tierPrices: [
      { minQty: 1, maxQty: 4, price: p.price, label: "1-4 unidades" },
      { minQty: 5, maxQty: 9, price: Math.round(p.price * 0.92), label: "5-9 unidades" },
      { minQty: 10, price: Math.round(p.price * 0.85), label: "10+ unidades (Mayorista)" },
    ],
    shippingWeight: 1,
    tags: [],
  };
}

const IMG = [
  "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1613665813446-82a78c468a1d?w=600&h=600&fit=crop",
  "/Alarma Hogar 8 Zonas Inalambrica.png",
  "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&h=600&fit=crop",
];
const img = (i: number): [string, string] => [IMG[i % IMG.length], IMG[(i + 4) % IMG.length]];

const EXTRA_PRODUCTS: Product[] = [
  // Iluminación LED & Neón Flex
  makeProduct({ id: "p024", categoryId: "iluminacion-led-neon", subcategory: "Paneles LED", name: "Panel LED 36W 600x600 4000K Marco Blanco", brand: "StarLight Pro", price: 12990, originalPrice: 18990, images: ["/Panel LED 36W 600x600 4000K Marco Blanco.png", "/Panel LED 36W 600x600 4000K Marco Blanco.png"], isFeatured: true }),
  makeProduct({ id: "p025", categoryId: "iluminacion-led-neon", subcategory: "Ampolletas & Paneles LED", name: "Ampolleta GU10 LED 7W 3000K Pack x4", brand: "Lumex", price: 6990, originalPrice: 9990, images: ["/Ampolleta GU10 LED 7W 3000K Pack x4.png", "/Ampolleta GU10 LED 7W 3000K Pack x4.png"], isBestSeller: true }),
  makeProduct({ id: "p026", categoryId: "iluminacion-led-neon", subcategory: "Drivers & Transformadores", name: "Driver LED 12V 100W IP67 Ultra Slim", brand: "Mean Well", price: 15990, images: img(2) }),
  // Tubos & Lámparas Especiales
  makeProduct({ id: "p027", categoryId: "tubos-lamparas-especiales", subcategory: "Tubos Germicidas UV-C", name: "Tubo Germicida UV-C 15W G13 50cm", brand: "Sanilux", price: 11990, originalPrice: 16990, images: ["/Tubo Germicida UV-C 15W G13 50cm.png", "/Tubo Germicida UV-C 15W G13 50cm.png"], isFeatured: true }),
  makeProduct({ id: "p028", categoryId: "tubos-lamparas-especiales", subcategory: "Lámparas Atrapa Mosquitos", name: "Lámpara Atrapa Mosquitos 20W USB", brand: "BugOff", price: 8990, images: img(4) }),
  makeProduct({ id: "p029", categoryId: "tubos-lamparas-especiales", subcategory: "Halógenas & HMI", name: "Lámpara Halógena HMI 575W Fresnel", brand: "StudioLite", price: 28990, images: img(5) }),
  makeProduct({ id: "p030", categoryId: "tubos-lamparas-especiales", subcategory: "Lámparas Infrarrojas", name: "Lámpara Infrarroja 250W Tapa Cerámica", brand: "Thermo", price: 9990, images: ["/Lampara Infrarroja 250W Tapa Ceramica.png", "/Lampara Infrarroja 250W Tapa Ceramica.png"] }),
  // Seguridad & Control Eléctrico
  makeProduct({ id: "p031", categoryId: "seguridad-control-electrico", subcategory: "Interruptores & Enchufes", name: "Enchufe Smart WiFi 16A Temporizador", brand: "Tuya Smart", price: 7990, originalPrice: 11990, images: ["/Enchufe Smart WiFi 16A Temporizador.png", "/Enchufe Smart WiFi 16A Temporizador.png"], isFeatured: true }),
  makeProduct({ id: "p032", categoryId: "seguridad-control-electrico", subcategory: "Cámaras de Seguridad", name: "Cámara Seguridad 2K IP66 Audio", brand: "SecureCam", price: 23990, images: ["/Camara Seguridad 2K IP66 Audio.png", "/Camara Seguridad 2K IP66 Audio.png"], isBestSeller: true }),
  makeProduct({ id: "p033", categoryId: "seguridad-control-electrico", subcategory: "Alarmas & Sensores", name: "Alarma Hogar 8 Zonas Inalámbrica", brand: "Defender", price: 19990, images: ["/Alarma Hogar 8 Zonas Inalambrica.png", "/Alarma Hogar 8 Zonas Inalambrica.png"] }),
  // Herramientas & Maquinarias
  makeProduct({ id: "p034", categoryId: "herramientas-maquinarias", subcategory: "Crimpadoras & Ponchadoras", name: "Crimpadora Modular RJ45/RJ11 Profesional", brand: "ProTool", price: 12990, originalPrice: 17990, images: ["/Crimpadora Modular RJ45RJ11 Profesional.png", "/Crimpadora Modular RJ45RJ11 Profesional.png"], isFeatured: true }),
  makeProduct({ id: "p035", categoryId: "herramientas-maquinarias", subcategory: "Sierras & Esmeriles", name: "Sierra Calar 800W 6 Velocidades", brand: "Bosch", price: 34990, images: ["/Sierra Calar 800W 6 Velocidades.png", "/Sierra Calar 800W 6 Velocidades.png"] }),
  makeProduct({ id: "p036", categoryId: "herramientas-maquinarias", subcategory: "Kit Electricista Profesional", name: "Kit Electricista 12 Piezas Acero", brand: "Starshop", price: 17990, originalPrice: 24990, images: ["/Kit Electricista 12 Piezas Acero.png", "/Kit Electricista 12 Piezas Acero.png"], isBestSeller: true }),
  // Fuentes de Poder & Soldadura
  makeProduct({ id: "p037", categoryId: "fuentes-poder-soldadura", subcategory: "Cautines & Pistolas", name: "Cautín 60W Temp Adjustable 200-480°C", brand: "Hakko", price: 9990, images: ["/Cautin 60W Temp Adjustable 200-480C.png", "/Cautin 60W Temp Adjustable 200-480C.png"] }),
  makeProduct({ id: "p038", categoryId: "fuentes-poder-soldadura", subcategory: "Fuentes de Laboratorio", name: "Fuente Laboratorio 30V 5A Display Dual", brand: "Korad", price: 32990, originalPrice: 42990, images: ["/Fuente Laboratorio 30V 5A Display Dual.png", "/Fuente Laboratorio 30V 5A Display Dual.png"], isFeatured: true }),
  makeProduct({ id: "p039", categoryId: "fuentes-poder-soldadura", subcategory: "Inversores & UPS", name: "Inversor 1000W 12V a 220V Onda Modificada", brand: "VoltMax", price: 27990, images: ["/Inversor 1000W 12V a 220V Onda Modificada.png", "/Inversor 1000W 12V a 220V Onda Modificada.png"] }),
  // Instrumentos de Medición & Térmicos
  makeProduct({ id: "p040", categoryId: "instrumentos-medicion", subcategory: "Medidores Láser", name: "Medidor Láser 40m Precisión 2mm", brand: "UNI-T", price: 14990, originalPrice: 19990, images: ["/Medidor Laser 40m Precisión 2mm.png", "/Medidor Laser 40m Precisión 2mm.png"], isBestSeller: true }),
  makeProduct({ id: "p041", categoryId: "instrumentos-medicion", subcategory: "Testers de Red & Cable", name: "Tester Red PoE & Cable RJ45", brand: "NOYAFA", price: 11990, images: ["/Tester Red PoE & Cable RJ45.png", "/Tester Red PoE & Cable RJ45.png"] }),
  // Pilas, Baterías & Cargadores
  makeProduct({ id: "p042", categoryId: "pilas-baterias-cargadores", subcategory: "Pilas de Litio 18650/21700", name: "Pila Litio 18650 3500mAh 10A", brand: "Samsung", price: 3990, images: ["/Pila Litio 18650 3500mAh 10A.png", "/Pila Litio 18650 3500mAh 10A.png"], isFeatured: true }),
  makeProduct({ id: "p043", categoryId: "pilas-baterias-cargadores", subcategory: "Baterías Selladas 12V", name: "Batería Sellada 12V 7Ah AGM", brand: "Vision", price: 14990, originalPrice: 19990, images: img(6) }),
  makeProduct({ id: "p044", categoryId: "pilas-baterias-cargadores", subcategory: "Power Banks & Estaciones", name: "Power Bank 20000mAh 65W PD", brand: "Baseus", price: 21990, images: ["/Power Bank 20000mAh 65W PD.png", "/Power Bank 20000mAh 65W PD.png"], isBestSeller: true }),
  // Electrónica & Misceláneos
  makeProduct({ id: "p045", categoryId: "electronica-miscelaneos", subcategory: "Componentes Electrónicos", name: "Kit Resistencias 600pzs 1/4W", brand: "ELEC", price: 5990, images: ["/Kit Resistencias 600pzs 1-4W.png", "/Kit Resistencias 600pzs 1-4W.png"] }),
  makeProduct({ id: "p046", categoryId: "electronica-miscelaneos", subcategory: "Protoboard & Arduino", name: "Protoboard 830 Puntos + Cables", brand: "MB", price: 4990, images: ["/Protoboard 830 Puntos Cables.png", "/Protoboard 830 Puntos Cables.png"] }),
  makeProduct({ id: "p047", categoryId: "electronica-miscelaneos", subcategory: "Cables & Conectores", name: "Cable UTP Cat6 1m Blindado", brand: "StarTech", price: 3490, images: ["/Cable UTP Cat6 1m Blindado.png", "/Cable UTP Cat6 1m Blindado.png"] }),
  makeProduct({ id: "p048", categoryId: "electronica-miscelaneos", subcategory: "Audio & Parlantes", name: "Parlante Bluetooth 20W IPX6", brand: "Tronsmart", price: 12990, originalPrice: 17990, images: ["/Parlante Bluetooth 20W IPX6.png", "/Parlante Bluetooth 20W IPX6.png"], isFeatured: true }),
  makeProduct({ id: "p049", categoryId: "electronica-miscelaneos", subcategory: "Iluminación Decorativa", name: "Tira LED Decorativa 3m APP RGB", brand: "FlexNeon", price: 8990, images: ["/Tira LED Decorativa 3m APP RGB.png", "/Tira LED Decorativa 3m APP RGB.png"] }),
];

export const products: Product[] = [
  {
    id: "p001",
    sku: "LED-PRO-200W-IP66",
    name: "Proyector LED 200W IP66 Luz Fría 6500K Alta Potencia SEC",
    slug: "proyector-led-200w-ip66",
    description: "Proyector LED de alta eficiencia para exterior, carcasa de aluminio inyectado, driver Mean Well incluido. Ideal para canchas, galpones y fachadas industriales. Vida útil 50.000 horas.",
    shortDescription: "Proyector LED 200W IP66 6500K - Uso industrial",
    categoryId: "iluminacion-led-neon",
    subcategory: "Proyectores LED",
    brand: "StarLight Pro",
    images: [
      "/Proyector LED 200W IP66 Luz Fria 6500K Alta Potencia SEC.png",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop",
    ],
    price: 45990,
    originalPrice: 69990,
    discount: 34,
    rating: 4.8,
    reviewCount: 342,
    stock: 120,
    soldCount: 890,
    isFlashSale: true,
    isFeatured: true,
    isBestSeller: true,
    secCertified: true,
    warranty: "2 años",
    specs: { Potencia: "200W", Lúmenes: "28.000 lm", IP: "IP66", Voltaje: "85-265V", Temperatura: "6500K" },
    tierPrices: [
      { minQty: 1, maxQty: 4, price: 45990, label: "1-4 unidades" },
      { minQty: 5, maxQty: 9, price: 41990, label: "5-9 unidades" },
      { minQty: 10, price: 38990, label: "10+ unidades (Mayorista)" },
    ],
    shippingWeight: 3.2,
    tags: ["proyector", "ip66", "exterior"],
  },
  {
    id: "p002",
    sku: "NEON-FLEX-12V-RGB-5M",
    name: "Cinta Neón Flex 12V RGB 5 Metros + Control Remoto IP65",
    slug: "cinta-neon-flex-rgb-5m",
    description: "Neón Flex de silicona flexible, corte cada 2.5cm, 120 LEDs/m, incluye control RF y fuente 12V 5A.",
    shortDescription: "Neón Flex RGB 12V 5m IP65 + Control Remoto",
    categoryId: "iluminacion-led-neon",
    subcategory: "Cintas LED & Neón Flex",
    brand: "FlexNeon",
    images: [
      "/Cinta Neón Flex 12V RGB 5 Metros-Control Remoto IP65.png",
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&h=600&fit=crop",
    ],
    price: 18990,
    originalPrice: 29990,
    discount: 37,
    rating: 4.6,
    reviewCount: 521,
    stock: 340,
    soldCount: 1240,
    isFlashSale: true,
    isFeatured: true,
    secCertified: true,
    warranty: "1 año",
    specs: { Voltaje: "12V DC", Largo: "5m", LEDs: "600 SMD2835", IP: "IP65", Control: "RF 44 teclas" },
    tierPrices: [
      { minQty: 1, maxQty: 9, price: 18990, label: "1-9 rollos" },
      { minQty: 10, price: 15990, label: "10+ rollos" },
    ],
    shippingWeight: 0.8,
    tags: ["neon", "rgb", "flexible"],
  },
  {
    id: "p003",
    sku: "MULT-FLKE-117-TRUE",
    name: "Multímetro Digital True RMS Fluke 117 Profesional Electricista",
    slug: "multimetro-fluke-117-true-rms",
    description: "Multímetro diseñado para electricistas comerciales e industriales. True RMS, VoltAlert, medición de frecuencia y capacitancia. CAT III 600V.",
    shortDescription: "Multímetro True RMS Fluke 117 CAT III 600V",
    categoryId: "instrumentos-medicion",
    subcategory: "Multímetros Digitales",
    brand: "Fluke",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=600&fit=crop",
    ],
    price: 189990,
    originalPrice: 229990,
    discount: 17,
    rating: 4.9,
    reviewCount: 128,
    stock: 45,
    soldCount: 310,
    isBestSeller: true,
    isB2B: true,
    secCertified: true,
    warranty: "3 años",
    specs: { Display: "6000 cuentas", Precisión: "0.5%", Alimentación: "9V", CAT: "CAT III 600V" },
    shippingWeight: 0.6,
    tags: ["multimetro", "fluke", "true rms"],
  },
  {
    id: "p004",
    sku: "CRIMP-HYD-16-300MM",
    name: "Prensa Hidráulica 16 Ton 16-300mm² + 8 Dados Hexagonales",
    slug: "prensa-hidraulica-16ton",
    description: "Prensa hidráulica manual para terminales de cobre y aluminio. Fuerza 16 toneladas, cabezal giratorio 360°, incluye maletín.",
    shortDescription: "Prensa Hidráulica 16T 16-300mm² 8 dados",
    categoryId: "herramientas-maquinarias",
    subcategory: "Prensas Hidráulicas",
    brand: "HydraPress",
    images: [
      "/Prensa Hidraulica 16 Ton 16-300mm8 Dados Hexagonales.png",
      "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=600&h=600&fit=crop",
    ],
    price: 89990,
    originalPrice: 129990,
    discount: 31,
    rating: 4.7,
    reviewCount: 89,
    stock: 28,
    soldCount: 156,
    isFlashSale: true,
    isB2B: true,
    secCertified: false,
    warranty: "1 año",
    specs: { Fuerza: "16 Ton", Rango: "16-300mm²", Peso: "5.8kg", Dados: "8 pares" },
    tierPrices: [
      { minQty: 1, maxQty: 4, price: 89990, label: "1-4" },
      { minQty: 5, price: 79990, label: "5+ (Contratista)" },
    ],
    shippingWeight: 6.1,
    tags: ["hidraulica", "crimpadora", "terminales"],
  },
  {
    id: "p005",
    sku: "TUBO-UVC-36W-G13",
    name: "Tubo Germicida UV-C 36W G13 120cm Esterilización O3 Free",
    slug: "tubo-germicida-uvc-36w",
    description: "Tubo UV-C 254nm para esterilización de aire y superficies. Sin ozono, vidrio cuarzo, vida útil 9000h. Para purificadores y hospitales.",
    shortDescription: "Tubo UV-C 36W G13 254nm 9000h sin ozono",
    categoryId: "tubos-lamparas-especiales",
    subcategory: "Tubos Germicidas UV-C",
    brand: "Sterilux",
    images: ["/Tubo Germicida UV-C 36W G13 120cm Esterilizacion O3 Free.png"],
    price: 12990,
    originalPrice: 18990,
    discount: 32,
    rating: 4.5,
    reviewCount: 67,
    stock: 210,
    soldCount: 430,
    isNew: true,
    secCertified: true,
    warranty: "6 meses",
    specs: { Potencia: "36W", Longitud: "120cm", Base: "G13", Vida: "9000h" },
    shippingWeight: 0.4,
    tags: ["uvc", "germicida", "esterilizacion"],
  },
  {
    id: "p006",
    sku: "EST-SOLD-JBC-245W",
    name: "Estación de Soldado JBC CD-2BE 130W + Punta C245 Control PID",
    slug: "estacion-soldado-jbc-130w",
    description: "Estación profesional con calentamiento en 2 segundos, recuperación térmica instantánea, modo reposo y hibernación.",
    shortDescription: "Estación Soldado JBC 130W PID C245",
    categoryId: "fuentes-poder-soldadura",
    subcategory: "Estaciones de Soldado",
    brand: "JBC",
    images: ["/Estación de Soldado JBC CD-2BE 130W Punta C245 Control PID.png"],
    price: 349990,
    rating: 4.9,
    reviewCount: 44,
    stock: 18,
    soldCount: 92,
    isB2B: true,
    isFeatured: true,
    secCertified: true,
    warranty: "2 años",
    specs: { Potencia: "130W", Temp: "90-450°C", Punta: "C245", Alimentación: "230V" },
    shippingWeight: 2.8,
    tags: ["estacion", "soldado", "jbc"],
  },
  {
    id: "p007",
    sku: "BATT-LITIO-18650-3000",
    name: "Pack 4x Batería Litio 18650 3000mAh 15A Samsung 30Q Original",
    slug: "pack-bateria-18650-4un",
    description: "Celdas 18650 originales Samsung INR18650-30Q, alta descarga 15A, ideal para linternas, vape y power tools. Con estuche.",
    shortDescription: "Pack 4x 18650 3000mAh Samsung 30Q 15A",
    categoryId: "pilas-baterias-cargadores",
    subcategory: "Pilas de Litio 18650/21700",
    brand: "Samsung SDI",
    images: ["/Pack 4x Bateria Litio 18650 3000mAh 15A Samsung 30Q.png"],
    price: 15990,
    originalPrice: 21990,
    discount: 27,
    rating: 4.8,
    reviewCount: 412,
    stock: 500,
    soldCount: 2100,
    isFlashSale: true,
    isBestSeller: true,
    secCertified: true,
    warranty: "6 meses",
    specs: { Capacidad: "3000mAh", Descarga: "15A", Voltaje: "3.6V", Ciclos: "250+" },
    shippingWeight: 0.2,
    tags: ["18650", "litio", "samsung"],
  },
  {
    id: "p008",
    sku: "DISY-2P-32A-6KA",
    name: "Disyuntor Termomagnético 2P 32A 6kA Curva C Riel DIN Schneider",
    slug: "disyuntor-2p-32a-schneider",
    description: "Disyuntor bipolar curva C, poder de corte 6kA, norma IEC60898. Para tableros domiciliarios e industriales.",
    shortDescription: "Disyuntor 2P 32A 6kA Curva C Schneider",
    categoryId: "seguridad-control-electrico",
    subcategory: "Disyuntores & Diferenciales",
    brand: "Schneider Electric",
    images: ["/Disyuntor Termomagnetico 2P 32A 6kA Curva C Riel DIN Schneider.png"],
    price: 6990,
    originalPrice: 9900,
    discount: 29,
    rating: 4.7,
    reviewCount: 298,
    stock: 800,
    soldCount: 1850,
    isBestSeller: true,
    secCertified: true,
    warranty: "1 año",
    specs: { Polos: "2P", Corriente: "32A", Corte: "6kA", Curva: "C" },
    tierPrices: [
      { minQty: 1, maxQty: 9, price: 6990, label: "1-9" },
      { minQty: 10, maxQty: 49, price: 5990, label: "10-49" },
      { minQty: 50, price: 4990, label: "50+ Mayorista" },
    ],
    shippingWeight: 0.2,
    tags: ["disyuntor", "termomagnetico", "schneider"],
  },
  {
    id: "p009",
    sku: "CAM-TERM-FLIR-C5",
    name: "Cámara Termográfica FLIR C5 WiFi 160x120 MSX -20 a 400°C",
    slug: "camara-termografica-flir-c5",
    description: "Cámara compacta con conectividad WiFi, FLIR Ignite Cloud, MSX y medición precisa. Para mantenimiento eléctrico y edilicio.",
    shortDescription: "Cámara FLIR C5 160x120 WiFi MSX 400°C",
    categoryId: "instrumentos-medicion",
    subcategory: "Cámaras Termográficas",
    brand: "FLIR",
    images: ["/Camara Termografica FLIR C5 WiFi 160x120 MSX -20 a 400C.png"],
    price: 699990,
    rating: 4.9,
    reviewCount: 21,
    stock: 9,
    soldCount: 38,
    isB2B: true,
    isFeatured: true,
    secCertified: false,
    warranty: "2 años",
    specs: { Resolución: "160x120", Rango: "-20 a 400°C", Precisión: "±3°C", WiFi: "Sí" },
    shippingWeight: 0.9,
    tags: ["termografica", "flir", "mantenimiento"],
  },
  {
    id: "p010",
    sku: "PELAC-AUTO-0.2-6MM",
    name: "Pelacables Automático 0.2-6mm² + Crimpador Terminales Ferrule",
    slug: "pelacables-automatico-0-2-6mm",
    description: "Pelacables autoajustable para cables 10-24 AWG, cuchillas de acero, crimpador integrado.",
    shortDescription: "Pelacables Automático 0.2-6mm² + Crimpador",
    categoryId: "herramientas-maquinarias",
    subcategory: "Pelacables & Alicates",
    brand: "Knipex Style",
    images: ["/Pelacables Automatico 02-6mm Crimpador Terminales.png"],
    price: 12990,
    originalPrice: 18990,
    discount: 32,
    rating: 4.6,
    reviewCount: 176,
    stock: 240,
    soldCount: 670,
    isFlashSale: true,
    secCertified: false,
    warranty: "1 año",
    specs: { Rango: "0.2-6mm²", AWG: "10-24", Largo: "210mm" },
    shippingWeight: 0.3,
    tags: ["pelacables", "ferrule", "automatico"],
  },
  {
    id: "p011",
    sku: "FUENTE-12V-30A-360W",
    name: "Fuente Switching 12V 30A 360W IP20 Transformador LED Mean Well",
    slug: "fuente-switching-12v-30a",
    description: "Fuente conmutada 110-240V a 12V DC, protección sobrecarga, cortocircuito y sobretensión. Para cintas LED y CCTV.",
    shortDescription: "Fuente 12V 30A 360W Switching IP20",
    categoryId: "fuentes-poder-soldadura",
    subcategory: "Transformadores 12V/24V",
    brand: "Mean Well LRS",
    images: ["https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=600&h=600&fit=crop"],
    price: 22990,
    originalPrice: 29990,
    discount: 23,
    rating: 4.8,
    reviewCount: 334,
    stock: 95,
    soldCount: 890,
    isBestSeller: true,
    secCertified: true,
    warranty: "2 años",
    specs: { Entrada: "110-240V", Salida: "12V 30A", Potencia: "360W", IP: "IP20" },
    shippingWeight: 1.1,
    tags: ["fuente", "switching", "meanwell"],
  },
  {
    id: "p012",
    sku: "AMP-LED-18W-EMB",
    name: "Panel LED Embutido 18W 6500K 1200lm Marco Aluminio Pack x6",
    slug: "panel-led-embutido-18w-pack6",
    description: "Pack 6 paneles redondos 18W luz fría, driver externo incluido, instalación rápida. Ideal oficinas y locales.",
    shortDescription: "Pack 6x Panel LED 18W 6500K Embutido",
    categoryId: "iluminacion-led-neon",
    subcategory: "Ampolletas & Paneles LED",
    brand: "StarLight",
    images: ["/panel LED Embutido 18W 6500K 1200lm Marco Aluminio Pack x6.png"],
    price: 29990,
    originalPrice: 49990,
    discount: 40,
    rating: 4.7,
    reviewCount: 203,
    stock: 150,
    soldCount: 560,
    isFlashSale: true,
    secCertified: true,
    warranty: "2 años",
    specs: { Potencia: "18W c/u", Flujo: "1200 lm", Diámetro: "225mm", Vida: "30.000h" },
    shippingWeight: 2.4,
    tags: ["panel", "embutido", "oficina"],
  },
  {
    id: "p013",
    sku: "CARG-INT-XTAR-VC4",
    name: "Cargador Inteligente XTAR VC4 4 Bahías Li-ion/Ni-MH USB Pantalla LCD",
    slug: "cargador-xtar-vc4-4bahias",
    description: "Cargador con detección automática, 4 canales independientes, pantalla LCD, compatible 10440 a 32650.",
    shortDescription: "Cargador XTAR VC4 4 bahías LCD USB",
    categoryId: "pilas-baterias-cargadores",
    subcategory: "Cargadores Inteligentes",
    brand: "XTAR",
    images: ["https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&h=600&fit=crop"],
    price: 19990,
    rating: 4.8,
    reviewCount: 98,
    stock: 76,
    soldCount: 240,
    isNew: true,
    secCertified: true,
    warranty: "1 año",
    specs: { Bahías: "4", Entrada: "5V 2.1A", Baterías: "Li-ion/Ni-MH", Display: "LCD" },
    shippingWeight: 0.3,
    tags: ["cargador", "xtar", "18650"],
  },
  {
    id: "p014",
    sku: "ARDUINO-UNO-R3-ORIG",
    name: "Arduino UNO R3 Original + Cable USB + Pack Resistencias & Jumpers",
    slug: "arduino-uno-r3-pack",
    description: "Placa original, micro ATmega328P, incluye cable USB y kit iniciación 200 piezas.",
    shortDescription: "Arduino UNO R3 Original + Kit 200pzs",
    categoryId: "electronica-miscelaneos",
    subcategory: "Protoboard & Arduino",
    brand: "Arduino",
    images: ["/Arduino UNO R3 Original Cable USBPack Resistencias & Jumpers.png"],
    price: 24990,
    originalPrice: 32990,
    discount: 24,
    rating: 4.9,
    reviewCount: 512,
    stock: 180,
    soldCount: 1450,
    isBestSeller: true,
    isFeatured: true,
    secCertified: false,
    warranty: "6 meses",
    specs: { MCU: "ATmega328P", Voltaje: "5V", Entradas: "14 digital, 6 analógicas", Memoria: "32KB" },
    shippingWeight: 0.5,
    tags: ["arduino", "uno", "protoboard"],
  },
  {
    id: "p015",
    sku: "TAB-EMP-36POLOS-IP65",
    name: "Tablero Eléctrico Embutido 36 Polos IP65 Transparente Riel DIN",
    slug: "tablero-36-polos-ip65",
    description: "Tablero para 36 módulos, puerta transparente, IP65, material ABS ignífugo.",
    shortDescription: "Tablero 36 Polos IP65 Transparente",
    categoryId: "seguridad-control-electrico",
    subcategory: "Tableros & Gabinetes",
    brand: "StarBox",
    images: ["/Disyuntor Termomagnetico 2P 32A 6kA Curva C Riel DIN Schneider.png"],
    price: 18990,
    rating: 4.6,
    reviewCount: 54,
    stock: 62,
    soldCount: 180,
    isB2B: true,
    secCertified: true,
    warranty: "1 año",
    specs: { Polos: "36", IP: "IP65", Material: "ABS", Puerta: "Transparente" },
    shippingWeight: 1.8,
    tags: ["tablero", "riel din", "ip65"],
  },
  {
    id: "p016",
    sku: "PIROM-UNI-T-UT300S",
    name: "Pirómetro Infrarrojo UNI-T UT300S -32 a 400°C Láser Emisividad Aj.",
    slug: "pirometro-uni-t-ut300s",
    description: "Termómetro sin contacto con puntero láser, emisividad ajustable, pantalla retroiluminada, auto apagado.",
    shortDescription: "Pirómetro UNI-T UT300S -32~400°C Láser",
    categoryId: "instrumentos-medicion",
    subcategory: "Pirómetros Infrarrojos",
    brand: "UNI-T",
    images: ["https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=600&h=600&fit=crop"],
    price: 24990,
    originalPrice: 35990,
    discount: 31,
    rating: 4.5,
    reviewCount: 87,
    stock: 110,
    soldCount: 320,
    isFlashSale: true,
    secCertified: false,
    warranty: "1 año",
    specs: { Rango: "-32~400°C", Precisión: "±1.5%", Distancia: "12:1", Láser: "Sí" },
    shippingWeight: 0.4,
    tags: ["pirometro", "infrarrojo", "temperatura"],
  },
  {
    id: "p017",
    sku: "HIGHBAY-UFO-150W-65K",
    name: "High Bay UFO LED 150W 6500K IP65 21000lm Meanwell + Cadena",
    slug: "high-bay-ufo-150w",
    description: "Campana industrial UFO 150W, driver Meanwell HBG, eficiencia 140lm/W, IP65, ideal galpones y bodegas 6-10m altura. Vida 50.000h, certificación SEC.",
    shortDescription: "High Bay UFO 150W 6500K IP65 21.000lm",
    categoryId: "iluminacion-led-neon",
    subcategory: "Iluminación Industrial",
    brand: "StarLight Pro",
    images: ["/High Bay UFO LED 150W 6500K IP65 21000lm Meanwell Cadena.png"],
    price: 59990,
    originalPrice: 89990,
    discount: 33,
    rating: 4.8,
    reviewCount: 94,
    stock: 75,
    soldCount: 420,
    isFeatured: true,
    isBestSeller: true,
    secCertified: true,
    warranty: "3 años",
    specs: { Potencia: "150W", Lúmenes: "21.000 lm", IP: "IP65", Driver: "Meanwell HBG" },
    tierPrices: [
      { minQty: 1, maxQty: 5, price: 59990, label: "1-5" },
      { minQty: 6, price: 54990, label: "6+ Mayorista" },
    ],
    shippingWeight: 4.1,
    tags: ["highbay", "ufo", "industrial"],
  },
  {
    id: "p018",
    sku: "TALADRO-20V-13MM-4AH",
    name: "Taladro Percutor Inalámbrico 20V 13mm Brushless 2x Batería 4Ah + Maletín",
    slug: "taladro-percutor-20v-brushless",
    description: "Taladro percutor brushless 60Nm, 2 velocidades, mandril 13mm metálico, 2 baterías 4Ah y cargador rápido. Ideal hormigón y metal.",
    shortDescription: "Taladro 20V 13mm Brushless 2x4Ah",
    categoryId: "herramientas-maquinarias",
    subcategory: "Taladros & Atornilladores",
    brand: "Makita Style",
    images: ["/Taladro Percutor Inalambrico 20V 13mm Brushless 2x Bateria 4Ah Maletin.png"],
    price: 129990,
    originalPrice: 179990,
    discount: 28,
    rating: 4.7,
    reviewCount: 156,
    stock: 42,
    soldCount: 310,
    isFeatured: true,
    secCertified: false,
    warranty: "1 año",
    specs: { Voltaje: "20V", Torque: "60Nm", Mandril: "13mm", Baterías: "2x 4Ah" },
    shippingWeight: 3.8,
    tags: ["taladro", "brushless", "inalambrico"],
  },
  {
    id: "p019",
    sku: "PINZA-UT210E-100A",
    name: "Pinza Amperimétrica UNI-T UT210E True RMS 100A AC/DC + NCV",
    slug: "pinza-amperimetrica-ut210e",
    description: "Mini pinza True RMS 100A AC/DC, mandíbula 17mm, NCV, resistencia y capacímetro. Auto rango, linterna, funda.",
    shortDescription: "Pinza UT210E 100A AC/DC True RMS",
    categoryId: "instrumentos-medicion",
    subcategory: "Pinzas Amperimétricas",
    brand: "UNI-T",
    images: ["/Pinza Amperimetrica UNI-T UT210E True RMS 100A ACDC NCV.png"],
    price: 39990,
    originalPrice: 54990,
    discount: 27,
    rating: 4.9,
    reviewCount: 203,
    stock: 88,
    soldCount: 560,
    isFeatured: true,
    isBestSeller: true,
    secCertified: true,
    warranty: "1 año",
    specs: { Corriente: "100A AC/DC", Apertura: "17mm", TrueRMS: "Sí", NCV: "Sí" },
    shippingWeight: 0.5,
    tags: ["pinza", "amperimetrica", "ut210e"],
  },
  {
    id: "p020",
    sku: "ATRAPA-MOSQ-UV-20W-80M2",
    name: "Lámpara Atrapa Mosquitos UV 20W 80m2 + Bandeja + Cadena Exterior",
    slug: "lampara-atrapa-mosquitos-20w",
    description: "Atrapa insectos UV-A 365nm, área 80m2, rejilla electrificada 2000V, bandeja extraíble, IPX4 para terrazas y locales.",
    shortDescription: "Atrapa Mosquitos UV 20W 80m2 IPX4",
    categoryId: "tubos-lamparas-especiales",
    subcategory: "Lámparas Atrapa Mosquitos",
    brand: "InsectPro",
    images: ["/Lampara Atrapa Mosquitos UV 20W 80m2 Bandeja Cadena Exterior.png"],
    price: 25990,
    originalPrice: 35990,
    discount: 28,
    rating: 4.6,
    reviewCount: 112,
    stock: 130,
    soldCount: 480,
    isFeatured: true,
    secCertified: true,
    warranty: "1 año",
    specs: { Potencia: "20W", Área: "80m2", Voltaje: "2000V", IP: "IPX4" },
    shippingWeight: 1.4,
    tags: ["mosquitos", "uv", "insectos"],
  },
  {
    id: "p021",
    sku: "CAUTIN-EST-60W-480C",
    name: "Cautín Estación 60W Temperatura Regulable 200-480°C Punta 900M + Soporte",
    slug: "cautin-estacion-60w",
    description: "Estación cautín 60W, control PID, calentamiento 15s, puntas 900M intercambiables, soporte metálico con esponja.",
    shortDescription: "Cautín 60W 200-480°C 900M",
    categoryId: "fuentes-poder-soldadura",
    subcategory: "Cautines & Pistolas",
    brand: "Yihua Style",
    images: ["/Cautin Estacion 60W Temperatura Regulable 200-480C Punta 900M .png"],
    price: 18990,
    originalPrice: 26990,
    discount: 30,
    rating: 4.5,
    reviewCount: 87,
    stock: 95,
    soldCount: 290,
    isFeatured: true,
    secCertified: false,
    warranty: "6 meses",
    specs: { Potencia: "60W", Temp: "200-480°C", Punta: "900M", Calentamiento: "15s" },
    shippingWeight: 0.9,
    tags: ["cautin", "estacion", "soldadura"],
  },
  {
    id: "p022",
    sku: "POWERBANK-20K-22W-QC",
    name: "Power Bank 20000mAh 22.5W QC PD Carga Rápida 2x USB + Type-C + Display",
    slug: "powerbank-20000mah-22w",
    description: "Batería externa 20000mAh, PD 20W + QC 22.5W, 3 salidas, display LED, carga simultánea, celdas Li-polymer grado A.",
    shortDescription: "Power Bank 20.000mAh 22.5W QC PD",
    categoryId: "pilas-baterias-cargadores",
    subcategory: "Power Banks & Estaciones",
    brand: "Baseus Style",
    images: ["/Power Bank 20000mAh 22 5W QC PD Carga Rapida 2x USB Type-C Display.png"],
    price: 19990,
    originalPrice: 29990,
    discount: 33,
    rating: 4.7,
    reviewCount: 245,
    stock: 210,
    soldCount: 980,
    isFeatured: true,
    secCertified: true,
    warranty: "1 año",
    specs: { Capacidad: "20.000mAh", Salida: "22.5W", Puertos: "3", Display: "LED" },
    shippingWeight: 0.45,
    tags: ["powerbank", "qc", "pd"],
  },
  {
    id: "p023",
    sku: "DOMO-WIFI-3GANG-TOUCH",
    name: "Kit Domótica WiFi Interruptor Touch 3 Gang + Enchufe Smart 16A Alexa/Google",
    slug: "kit-domotica-wifi-touch",
    description: "Kit smart home WiFi 2.4GHz, control por app Tuya/Smart Life, comando voz Alexa/Google, temporizador y escenas. Sin hub.",
    shortDescription: "Kit Domótica WiFi 3 Gang Touch + Enchufe",
    categoryId: "seguridad-control-electrico",
    subcategory: "Domótica & Smart Home",
    brand: "Tuya Smart",
    images: ["/Kit Domotica WiFi Interruptor Touch 3 Gang Enchufe Smart 16A AlexaGoogle.png"],
    price: 32990,
    originalPrice: 45990,
    discount: 28,
    rating: 4.6,
    reviewCount: 134,
    stock: 68,
    soldCount: 360,
    isFeatured: true,
    secCertified: true,
    warranty: "1 año",
    specs: { Protocolo: "WiFi 2.4GHz", Voz: "Alexa/Google", App: "Tuya", Carga: "16A" },
    shippingWeight: 0.6,
    tags: ["domotica", "wifi", "smart"],
  },
  ...EXTRA_PRODUCTS,
];

export const shippingRegions = [
  { region: "Región Metropolitana", cost: 3990, estimatedDays: "24-48h" },
  { region: "Valparaíso / O'Higgins", cost: 4990, estimatedDays: "48-72h" },
  { region: "Norte (Arica - Coquimbo)", cost: 6990, estimatedDays: "3-4 días" },
  { region: "Sur (Maule - Los Lagos)", cost: 6990, estimatedDays: "3-4 días" },
  { region: "Extremo Sur & Norte", cost: 9990, estimatedDays: "4-6 días" },
];

export type ChileRegionZone = "rm" | "central" | "norte" | "sur" | "extremo";

export const chileRegionCosts: Record<ChileRegionZone, { cost: number; estimatedDays: string }> = {
  rm: { cost: 3990, estimatedDays: "24-48h" },
  central: { cost: 4990, estimatedDays: "48-72h" },
  norte: { cost: 6990, estimatedDays: "3-4 días" },
  sur: { cost: 6990, estimatedDays: "3-4 días" },
  extremo: { cost: 9990, estimatedDays: "4-6 días" },
};

export const chileRegions: { name: string; zone: ChileRegionZone; communes: string[] }[] = [
  {
    name: "Región de Arica y Parinacota",
    zone: "norte",
    communes: ["Arica", "Camarones", "Putre", "General Lagos"],
  },
  {
    name: "Región de Tarapacá",
    zone: "norte",
    communes: ["Iquique", "Alto Hospicio", "Pozo Almonte", "Camiña", "Colchane", "Huara", "Pica"],
  },
  {
    name: "Región de Antofagasta",
    zone: "norte",
    communes: ["Antofagasta", "Mejillones", "Sierra Gorda", "Taltal", "Calama", "Ollagüe", "San Pedro de Atacama", "Tocopilla", "María Elena"],
  },
  {
    name: "Región de Atacama",
    zone: "norte",
    communes: ["Copiapó", "Caldera", "Tierra Amarilla", "Chañaral", "Diego de Almagro", "Vallenar", "Huasco", "Freirina", "Alto del Carmen"],
  },
  {
    name: "Región de Coquimbo",
    zone: "norte",
    communes: ["La Serena", "Coquimbo", "Vicuña", "Andacollo", "Paiguano", "Río Hurtado", "Illapel", "Salamanca", "Los Vilos", "Canela", "Ovalle", "Combarbalá", "Monte Patria", "Punitaqui"],
  },
  {
    name: "Región de Valparaíso",
    zone: "central",
    communes: ["Valparaíso", "Casablanca", "Concón", "Quintero", "Puchuncaví", "Juan Fernández", "Viña del Mar", "Quilpué", "Villa Alemana", "Limache", "Olmué", "San Antonio", "Cartagena", "El Quisco", "Algarrobo", "Santo Domingo", "San Felipe", "Santa María", "Los Andes", "Calle Larga", "Rinconada", "Panquehue", "La Ligua", "Papudo", "Petorca", "Zapallar", "Cabildo", "Catemu", "Quillota", "La Cruz", "Hijuelas", "Nogales", "Isla de Pascua"],
  },
  {
    name: "Región Metropolitana de Santiago",
    zone: "rm",
    communes: ["Santiago", "Cerrillos", "Cerro Navia", "Conchalí", "El Bosque", "Estación Central", "Huechuraba", "Independencia", "La Cisterna", "La Granja", "La Florida", "La Pintana", "Las Condes", "Lo Barnechea", "Lo Espejo", "Lo Prado", "Macul", "Maipú", "Ñuñoa", "Pedro Aguirre Cerda", "Peñalolén", "Providencia", "Pudahuel", "Quilicura", "Quinta Normal", "Recoleta", "Renca", "San Bernardo", "San Joaquín", "San Miguel", "San Ramón", "Vitacura", "Puente Alto", "San José de Maipú", "Colina", "Lampa", "Til Til", "Calera de Tango", "Buin", "Paine", "Melipilla", "Curacaví", "Alhué", "San Pedro", "María Pinto", "Talagante", "El Monte", "Isla de Maipo", "Padre Hurtado", "Peñaflor"],
  },
  {
    name: "Región del Libertador General Bernardo O'Higgins",
    zone: "central",
    communes: ["Rancagua", "Codegua", "Coínco", "Coltauco", "Doñihue", "Graneros", "Las Cabras", "Machalí", "Malloa", "Mostazal", "Olivar", "Peumo", "Pichidegua", "Quinta de Tilcoco", "Rengo", "Requínoa", "San Vicente", "Pichilemu", "La Estrella", "Litueche", "Marchihue", "Navidad", "Paredones", "San Fernando", "Chépica", "Chimbarongo", "Lolol", "Nancagua", "Palmilla", "Peralillo", "Placilla", "Pumanque", "Santa Cruz"],
  },
  {
    name: "Región del Maule",
    zone: "sur",
    communes: ["Talca", "Constitución", "Curepto", "Curicó", "Hualañé", "Licantén", "Molina", "Teno", "Vichuquén", "Rauco", "Romeral", "Sagrada Familia", "San Clemente", "San Rafael", "Pelarco", "Pencahue", "Maule", "San Javier", "Villa Alegre", "Yerbas Buenas", "Linares", "Colbún", "Longaví", "Parral", "Retiro", "Cauquenes", "Chanco", "Pelluhue", "Empedrado"],
  },
  {
    name: "Región de Ñuble",
    zone: "sur",
    communes: ["Chillán", "Chillán Viejo", "Bulnes", "Cobquecura", "Coelemu", "Coihueco", "El Carmen", "Ninhue", "Ñiquén", "Pemuco", "Pinto", "Quillón", "Quirihue", "Ránquil", "San Carlos", "San Fabián", "San Ignacio", "San Nicolás", "Treguaco", "Yungay", "Portezuelo"],
  },
  {
    name: "Región del Biobío",
    zone: "sur",
    communes: ["Concepción", "Coronel", "Chiguayante", "Florida", "Hualqui", "Lota", "Penco", "San Pedro de la Paz", "Santa Juana", "Talcahuano", "Tomé", "Hualpén", "Lebu", "Arauco", "Cañete", "Contulmo", "Curanilahue", "Los Álamos", "Tirúa", "Los Ángeles", "Antuco", "Cabrero", "Laja", "Mulchén", "Nacimiento", "Negrete", "Quilaco", "Quilleco", "San Rosendo", "Santa Bárbara", "Tucapel", "Yumbel", "Alto Biobío"],
  },
  {
    name: "Región de La Araucanía",
    zone: "sur",
    communes: ["Temuco", "Carahue", "Cunco", "Curarrehue", "Freire", "Galvarino", "Gorbea", "Lautaro", "Loncoche", "Melipeuco", "Nueva Imperial", "Padre las Casas", "Perquenco", "Pitrufquén", "Pucón", "Saavedra", "Teodoro Schmidt", "Toltén", "Villarrica", "Cholchol", "Angol", "Collipulli", "Curacautín", "Ercilla", "Lonquimay", "Los Sauces", "Lumaco", "Purén", "Renaico", "Traiguén", "Victoria"],
  },
  {
    name: "Región de Los Ríos",
    zone: "sur",
    communes: ["Valdivia", "Corral", "Lanco", "Los Lagos", "Máfil", "Mariquina", "Paillaco", "Panguipulli", "Río Bueno", "La Unión", "Futrono", "Lago Ranco"],
  },
  {
    name: "Región de Los Lagos",
    zone: "sur",
    communes: ["Puerto Montt", "Calbuco", "Cochamó", "Fresia", "Frutillar", "Los Muermos", "Llanquihue", "Maullín", "Puerto Varas", "Castro", "Ancud", "Chonchi", "Curaco de Vélez", "Dalcahue", "Puqueldón", "Queilén", "Quellón", "Quemchi", "Quinchao", "Osorno", "Puerto Octay", "Purranque", "Puyehue", "Río Negro", "San Juan de la Costa", "San Pablo", "Chaitén", "Futaleufú", "Hualaihué", "Palena"],
  },
  {
    name: "Región de Aysén del General Carlos Ibáñez del Campo",
    zone: "extremo",
    communes: ["Coihaique", "Lago Verde", "Aysén", "Cisnes", "Guaitecas", "Chile Chico", "Coyhaique", "O'Higgins", "Río Ibáñez", "Tortel"],
  },
  {
    name: "Región de Magallanes y la Antártica Chilena",
    zone: "extremo",
    communes: ["Punta Arenas", "Cabo de Hornos", "Laguna Blanca", "Río Verde", "San Gregorio", "Puerto Natales", "Torres del Paine", "Porvenir", "Primavera", "Timaukel"],
  },
];

export const heroSlides = [
  {
    id: 2,
    title: "Venta Mayorista B2B",
    subtitle: "Descuentos por volumen hasta 30%",
    description: "Atención a industrias, constructoras y distribuidores",
    cta: "Ser Cliente B2B",
    image: "/b2b.jpg",
    bg: "from-emerald-600 to-teal-700",
  },
  {
    id: 3,
    title: "Iluminación Industrial LED",
    subtitle: "Hasta 50% OFF + Envío Gratis RM",
    description: "Proyectores, High Bay y alumbrado público certificado SEC",
    cta: "Ver Ofertas",
    image: "/LED.png",
    bg: "from-amber-500 to-orange-600",
  },
  {
    id: 1,
    title: "Herramientas Profesionales",
    subtitle: "Prensas Hidráulicas 16T desde $89.990",
    description: "Para contratistas y electricistas - Garantía total",
    cta: "Cotizar Ahora",
    image: "/hydraulic.jpg",
    bg: "from-slate-700 to-slate-900",
  },
];

// formatCLP vive en src/lib/utils.ts — re-exportado para mantener la API de este módulo.
export { formatCLP } from "./utils";

export function discountPercent(original: number, current: number) {
  return Math.round(((original - current) / original) * 100);
}

export function getChileShipping(regionName: string, subtotal: number) {
  const region = chileRegions.find((r) => r.name === regionName);
  const zone = region?.zone ?? "rm";
  const info = chileRegionCosts[zone];
  const free = subtotal >= 49990 && zone === "rm";
  return { cost: free ? 0 : info.cost, estimatedDays: info.estimatedDays, free };
}
